#server:
#  port: 4020
spring:
  #h2:
  #  console:
  #    enabled: true
  #    path: /h2-console
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://containers-us-west-175.railway.app:7087/railway
    username: postgres
    password: xp0FrixBfQYjcMrbkdsm
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  #  database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: true
        use_sql_comments: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: alpha

